### ISSUE TITLE
Cannot create normalized xyzVector from vector of length() zero

### ISSUE THREAD

**Issue by pacho2** [martinpacesa/BindCraft#113]
Hello,

I am trying to run BindCraft with the example PDL1 file. The only change compared with current defaults is to obtain smaller ligands:
```
--- a/settings_target/PDL1.json
+++ b/settings_target/PDL1.json
@@ -1,9 +1,9 @@
 {
-    "design_path": "/content/drive/My Drive/BindCraft/PDL1/",
+    "design_path": "Designs/PDL1/",
     "binder_name": "PDL1",
-    "starting_pdb": "/content/bindcraft/example/PDL1.pdb",
+    "starting_pdb": "./example/PDL1.pdb",
     "chains": "A",
     "target_hotspot_residues": "56",
-    "lengths": [65, 150],
+    "lengths": [10, 40],
     "number_of_final_designs": 100
 }
```

I am running the latest git version up to commit:
https://github.com/martinpacesa/BindCraft/commit/475181f14e48d06bb4e03ec564807036284a5243

When running it as:
```
$ python -u ./bindcraft.py --settings './settings_target/PDL1.json' --filters './settings_filters/default_filters.json' --advanced './settings_advanced/default_4stage_multimer.json'
```

It runs for some hours but, at some point, it fails with this error:
```
Stage 4: PSSM Semigreedy Optimisation
Running semigreedy optimization...
126 models [3] recycles 1 hard 1 soft 0 temp 1 loss 4.83 helix 1.12 pae 0.20 i_pae 0.13 con 2.71 i_con 2.29 plddt 0.79 ptm 0.84 i_ptm 0.72 rg 0.13
127 models [4] recycles 1 hard 1 soft 0 temp 1 loss 7.46 helix 3.92 pae 0.58 i_pae 0.51 con 3.81 i_con 3.89 plddt 0.38 ptm 0.76 i_ptm 0.18 rg 1.86
128 models [1] recycles 1 hard 1 soft 0 temp 1 loss 6.99 helix 4.44 pae 0.58 i_pae 0.53 con 3.60 i_con 3.90 plddt 0.42 ptm 0.76 i_ptm 0.17 rg 1.44
129 models [3] recycles 1 hard 1 soft 0 temp 1 loss 7.24 helix 4.19 pae 0.61 i_pae 0.58 con 3.71 i_con 3.96 plddt 0.39 ptm 0.75 i_ptm 0.15 rg 1.42
130 models [2] recycles 1 hard 1 soft 0 temp 1 loss 8.06 helix 1.13 pae 0.57 i_pae 0.49 con 4.23 i_con 3.58 plddt 0.37 ptm 0.77 i_ptm 0.21 rg 0.70
131 models [1] recycles 1 hard 1 soft 0 temp 1 loss 7.63 helix 0.88 pae 0.51 i_pae 0.41 con 4.06 i_con 3.63 plddt 0.36 ptm 0.78 i_ptm 0.25 rg -0.50
132 models [1] recycles 1 hard 1 soft 0 temp 1 loss 7.83 helix 0.82 pae 0.50 i_pae 0.40 con 4.03 i_con 3.62 plddt 0.40 ptm 0.78 i_ptm 0.25 rg 0.27
133 models [3] recycles 1 hard 1 soft 0 temp 1 loss 7.67 helix 1.21 pae 0.57 i_pae 0.47 con 4.12 i_con 3.67 plddt 0.33 ptm 0.77 i_ptm 0.22 rg -0.47
134 models [4] recycles 1 hard 1 soft 0 temp 1 loss 7.80 helix 1.72 pae 0.57 i_pae 0.45 con 4.11 i_con 3.62 plddt 0.28 ptm 0.77 i_ptm 0.22 rg 0.70
135 models [2] recycles 1 hard 1 soft 0 temp 1 loss 8.39 helix 0.94 pae 0.53 i_pae 0.43 con 4.54 i_con 3.51 plddt 0.41 ptm 0.77 i_ptm 0.26 rg 0.89
136 models [4] recycles 1 hard 1 soft 0 temp 1 loss 8.59 helix 0.78 pae 0.45 i_pae 0.35 con 4.90 i_con 3.18 plddt 0.41 ptm 0.79 i_ptm 0.32 rg 1.46
137 models [0] recycles 1 hard 1 soft 0 temp 1 loss 8.62 helix 0.74 pae 0.48 i_pae 0.40 con 4.88 i_con 3.49 plddt 0.42 ptm 0.78 i_ptm 0.26 rg 0.46
138 models [3] recycles 1 hard 1 soft 0 temp 1 loss 8.39 helix 0.94 pae 0.49 i_pae 0.39 con 4.79 i_con 3.32 plddt 0.44 ptm 0.78 i_ptm 0.29 rg 0.83
139 models [4] recycles 1 hard 1 soft 0 temp 1 loss 8.79 helix 0.76 pae 0.48 i_pae 0.37 con 4.94 i_con 3.29 plddt 0.41 ptm 0.78 i_ptm 0.29 rg 1.54
140 models [2] recycles 1 hard 1 soft 0 temp 1 loss 8.81 helix 0.90 pae 0.53 i_pae 0.43 con 4.89 i_con 3.49 plddt 0.39 ptm 0.77 i_ptm 0.25 rg 1.16
Trajectory successful, final pLDDT: 0.79
Starting trajectory took: 0 hours, 3 minutes, 37 seconds

Traceback (most recent call last):
  File "/home/pacho/BindCraft-1.2.0_post20241124/./bindcraft.py", line 125, in <module>
    pr_relax(trajectory_pdb, trajectory_relaxed)
  File "/home/pacho/BindCraft-1.2.0_post20241124/functions/pyrosetta_utils.py", line 224, in pr_relax
    fastrelax.apply(pose)
RuntimeError: 

File: /home/benchmark/rosetta/source/src/core/kinematics/Stub.cc:106
Error in Stub::from_four_points(): 

File: /home/benchmark/rosetta/source/build/PyRosetta/Linux-5.4.0-84-generic-x86_64-with-glibc2.27/clang-6.0.0/python-3.10/release.serialization.thread/source/src/numeric/xyzVector.hh:654
Cannot create normalized xyzVector from vector of length() zero.  Error occurred when trying to normalize the vector between points A and B.  A=[24,000000,-63,000000,-31,000000], B=[24,000000,-63,000000,-31,000000].
```

I have tried to modify the lengths, but sooner or later, it ends up with the same error

Thanks a lot for your help

**Comment by martinpacesa** [comment]
Hi, this is probably not a problem of the binder lengths, but a problem of Rosetta. Unfortunately I am not sure how to help there, but you can ask over at the Rosetta forums

**Comment by pacho2** [comment]
For now, I have been trying with another PDB and different lengths... and it's the same problem (always at "Stage 4 PSSM..." after "140" step). I will try to change pyrosetta version for seeing if it changes anything

**Comment by pacho2** [comment]
Hello,

Sadly, it's the same with the 3stage, it fails just after Stage 3 in that case:
```
Stage 3: running (hard)
121 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 4.11 helix 0.37 pae 0.22 i_pae 0.23 con 4.95 i_con 2.24 plddt 0.83 ptm 0.89 i_ptm 0.79
122 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 4.96 helix 0.68 pae 0.53 i_pae 0.57 con 4.22 i_con 3.59 plddt 0.49 ptm 0.81 i_ptm 0.38
123 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 4.58 helix 0.52 pae 0.39 i_pae 0.42 con 4.59 i_con 3.01 plddt 0.66 ptm 0.85 i_ptm 0.56
124 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 4.80 helix 0.61 pae 0.44 i_pae 0.47 con 4.47 i_con 3.30 plddt 0.57 ptm 0.83 i_ptm 0.48
125 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 4.58 helix 0.52 pae 0.39 i_pae 0.42 con 4.59 i_con 3.01 plddt 0.66 ptm 0.85 i_ptm 0.56
Trajectory successful, final pLDDT: 0.87
Starting trajectory took: 0 hours, 6 minutes, 48 seconds

Traceback (most recent call last):
  File "/home/pacho/BindCraft-1.2.0_post20241124/./bindcraft.py", line 125, in <module>
    pr_relax(trajectory_pdb, trajectory_relaxed)
  File "/home/pacho/BindCraft-1.2.0_post20241124/functions/pyrosetta_utils.py", line 224, in pr_relax
    fastrelax.apply(pose)
RuntimeError: 

File: /home/benchmark/rosetta/source/src/core/kinematics/Stub.cc:106
Error in Stub::from_four_points(): 

File: /home/benchmark/rosetta/source/build/PyRosetta/Linux-5.4.0-84-generic-x86_64-with-glibc2.27/clang-6.0.0/python-3.10/release.serialization.thread/source/src/numeric/xyzVector.hh:654
Cannot create normalized xyzVector from vector of length() zero.  Error occurred when trying to normalize the vector between points A and B.  A=[32,000000,63,000000,49,000000], B=[32,000000,63,000000,49,000000].
```

Then, it seems the problem happens when fastrelax.apply(pose) (from functions/pyrosetta_utils.py) is called

**Comment by martinpacesa** [comment]
are you running it on a custom trimmed PDB?

**Comment by pacho2** [comment]
Hi,

No, it is the unmodified example/PDL1.pdb file:
https://github.com/martinpacesa/BindCraft/blob/main/example/PDL1.pdb

**Comment by pacho2** [comment]
And this is an example of a Designs/PDL1/Trajectory pdb file (if I understood correctly from the code, I think that one is the one that goes to fastrelax and dies later 🤔
[PDL1_l23_s495156.pdb.txt](https://github.com/user-attachments/files/18027284/PDL1_l23_s495156.pdb.txt)

**Comment by martinpacesa** [comment]
Ah, perhaps it's your design path. Try to put in the absolute file path

**Comment by pacho2** [comment]
Sadly, it is the same:
```
Running semigreedy optimization...
126 models [3] recycles 1 hard 1 soft 0 temp 1 loss 3.09 helix 1.77 pae 0.13 i_pae 0.07 con 1.73 i_con 1.41 plddt 0.93 ptm 0.88 i_ptm 0.87 rg 1.38
127 models [2] recycles 1 hard 1 soft 0 temp 1 loss 3.24 helix 1.54 pae 0.13 i_pae 0.07 con 1.83 i_con 1.40 plddt 0.93 ptm 0.88 i_ptm 0.87 rg 1.32
128 models [0] recycles 1 hard 1 soft 0 temp 1 loss 3.27 helix 1.62 pae 0.12 i_pae 0.08 con 1.84 i_con 1.44 plddt 0.92 ptm 0.89 i_ptm 0.87 rg 1.32
129 models [0] recycles 1 hard 1 soft 0 temp 1 loss 3.39 helix 1.64 pae 0.14 i_pae 0.08 con 1.90 i_con 1.51 plddt 0.90 ptm 0.87 i_ptm 0.85 rg 1.31
130 models [2] recycles 1 hard 1 soft 0 temp 1 loss 4.70 helix 1.32 pae 0.20 i_pae 0.14 con 2.27 i_con 2.30 plddt 0.83 ptm 0.82 i_ptm 0.70 rg 1.33
131 models [0] recycles 1 hard 1 soft 0 temp 1 loss 3.75 helix 1.80 pae 0.14 i_pae 0.09 con 2.13 i_con 1.65 plddt 0.89 ptm 0.86 i_ptm 0.84 rg 1.42
132 models [0] recycles 1 hard 1 soft 0 temp 1 loss 3.94 helix 1.39 pae 0.15 i_pae 0.09 con 2.21 i_con 1.62 plddt 0.88 ptm 0.87 i_ptm 0.84 rg 1.47
133 models [2] recycles 1 hard 1 soft 0 temp 1 loss 7.27 helix 1.07 pae 0.50 i_pae 0.47 con 3.35 i_con 3.72 plddt 0.50 ptm 0.70 i_ptm 0.23 rg 0.63
134 models [3] recycles 1 hard 1 soft 0 temp 1 loss 4.69 helix 1.30 pae 0.19 i_pae 0.12 con 2.41 i_con 2.12 plddt 0.84 ptm 0.84 i_ptm 0.77 rg 1.44
135 models [0] recycles 1 hard 1 soft 0 temp 1 loss 4.80 helix 1.42 pae 0.18 i_pae 0.13 con 2.53 i_con 2.15 plddt 0.83 ptm 0.85 i_ptm 0.78 rg 1.47
136 models [1] recycles 1 hard 1 soft 0 temp 1 loss 4.15 helix 1.31 pae 0.16 i_pae 0.10 con 2.31 i_con 1.71 plddt 0.87 ptm 0.86 i_ptm 0.84 rg 1.45
137 models [4] recycles 1 hard 1 soft 0 temp 1 loss 7.58 helix 1.05 pae 0.50 i_pae 0.44 con 3.61 i_con 3.65 plddt 0.48 ptm 0.71 i_ptm 0.25 rg 1.03
138 models [4] recycles 1 hard 1 soft 0 temp 1 loss 6.78 helix 1.05 pae 0.39 i_pae 0.34 con 3.20 i_con 3.32 plddt 0.59 ptm 0.74 i_ptm 0.36 rg 1.08
139 models [3] recycles 1 hard 1 soft 0 temp 1 loss 7.28 helix 1.06 pae 0.47 i_pae 0.45 con 3.31 i_con 3.66 plddt 0.52 ptm 0.72 i_ptm 0.26 rg 1.04
140 models [3] recycles 1 hard 1 soft 0 temp 1 loss 7.17 helix 1.04 pae 0.48 i_pae 0.45 con 3.29 i_con 3.61 plddt 0.52 ptm 0.72 i_ptm 0.26 rg 0.85
Trajectory successful, final pLDDT: 0.93
Starting trajectory took: 0 hours, 4 minutes, 42 seconds

Traceback (most recent call last):
  File "/home/pacho/BindCraft-1.2.0_post20241124/./bindcraft.py", line 125, in <module>
    pr_relax(trajectory_pdb, trajectory_relaxed)
  File "/home/pacho/BindCraft-1.2.0_post20241124/functions/pyrosetta_utils.py", line 224, in pr_relax
    fastrelax.apply(pose)
RuntimeError: 

File: /home/benchmark/rosetta/source/src/core/kinematics/Stub.cc:106
Error in Stub::from_four_points(): 

File: /home/benchmark/rosetta/source/build/PyRosetta/Linux-5.4.0-84-generic-x86_64-with-glibc2.27/clang-6.0.0/python-3.10/release.serialization.thread/source/src/numeric/xyzVector.hh:654
Cannot create normalized xyzVector from vector of length() zero.  Error occurred when trying to normalize the vector between points A and B.  A=[28,000000,-61,000000,-10,000000], B=[28,000000,-61,000000,-10,000000].
```

Now I have:
```
--- a/settings_target/PDL1.json
+++ b/settings_target/PDL1.json
@@ -1,9 +1,9 @@
 {
-    "design_path": "/content/drive/My Drive/BindCraft/PDL1/",
+    "design_path": "/home/pacho/BindCraft-1.2.0_post20241124/Designs/PDL1",
     "binder_name": "PDL1",
-    "starting_pdb": "/content/bindcraft/example/PDL1.pdb",
+    "starting_pdb": "/home/pacho/BindCraft-1.2.0_post20241124/example/PDL1.pdb",
     "chains": "A",
     "target_hotspot_residues": "56",
-    "lengths": [65, 150],
+    "lengths": [20, 40],
     "number_of_final_designs": 100
 }
```

But I also tried without changing the "lengths" and appending "/" to the end of design_path without success :-(

**Comment by martinpacesa** [comment]
Very strange, unfortunately I am not sure how to debug this Rosetta error, sorry 🙏🏻

**Comment by pacho2** [comment]
No problem. I am also surprised that you cannot reproduce it locally as I work on a fresh cloned repo with a newly created miniconda environment :/

**Comment by pacho2** [comment]
I would leave it opened as it is not solved, and maybe other people will hit it too (or they could figure out something). 

I am now trying to see if it's a problem with the generated  "trajectory_pdb" file, but without success yet :(

**Comment by pacho2** [comment]
For now I tried forcing it to use the regular PDL1.pdb instead of the trajectory_pdb file without success (same error). But a simpler pyrosetta script works fine with the provided PDBs:
```
# import PyRosetta library
from pyrosetta import *
init('-ignore_unrecognized_res -ignore_zero_occupancy -holes:dalphaball {advanced_settings["dalphaball_path"]} -corrections::beta_nov16 true -relax:default_repeats 1')
from functions import *

pose = pose_from_file("./example/PDL1_l23_s495156.pdb.txt")

scorefxn = rosetta.core.scoring.get_score_function()
fastrelax = rosetta.protocols.relax.FastRelax(scorefxn, 1)
fastrelax.apply(pose)
```

**Comment by HS-11** [comment]
Unfortunately, I can "reproduce" your problem every single time... Both with PDL1 and a protein of mine, and also on two very different (but similarly weak) machines. Either Ubuntu 18.04 with a GTX 980Ti or Ubuntu 22.04 with a _slightly_ larger Quadro M4000. Conda with CUDA 12.6 and flax downgraded to 0.9.0. as described in #60.

What was strange with both of my installations: Running install_bindcraft.sh, I get jax and jaxlib, but not jax-cuda12-pjrt and jax-cuda12-plugin. To get the program to even start, I successfully (?) installed 0.4.30 as described in #114, but then it crashes with the error discussed here. 

Maybe there is something else missing? Could someone please share a _conda list_ of a working setup?

**Comment by HS-11** [comment]
Well, I found an unexpected solution.

For me, it works **only without XServer** running where the program is executed, i.e. using ssh or doing the Ctrl+Alt+Fx.

I currently run jax and jaxlib 0.4.28 and on one machine I ran into the issue with DAlphaball and fixed it as in #65, but I'm not sure if that's even related.

**Comment by pacho2** [comment]
It seems to work :D 

Thanks a lot

Unsure if it 's a bug on cuda/nvidia-driver side then :thinking:  I will comment it on pyrosetta bug (just in case). I was wondering if it would be possible to create a Troubleshooting page. Other github projects have it in a "wiki" inside the same github. That could be useful to store this kind of workarounds for other people hitting similar issues (until a better fix is possible).

Best regards

**Comment by martinpacesa** [comment]
We will set up one sometime around March, once the new version of the pipeline is released

**Comment by pacho2** [comment]
Thanks!

**Comment by pacho2** [comment]
Hello,

I wanted to simply say that unsetting DISPLAY variable "solves" the problem. Then, maybe the variable could be unset from bindcraft.py 🤔 

Thanks a lot

**Comment by pacho2** [comment]
Running:
```
$ unset DISPLAY
```

Just before running bindcraft should work
