### ISSUE TITLE
ValueError: std::bad_cast

### ISSUE THREAD

**Issue by uuwuyi** [martinpacesa/BindCraft#15]
Hi @martinpacesa 

I got the error message below. Could you help me with this please! Many thanks!

```
PyRosetta-4 2024 [Rosetta PyRosetta4.Release.python39.ubuntu 2024.24+release.ca096dac4f43ee5ee195f87f3703a520fcf60cf9 2024-06-14T16:57:57] retrieved from: http://www.pyrosetta.org
Starting trajectory: PDL1_l98_s133578
Traceback (most recent call last):
  File "/iridisfs/scratch/binder/BindCraft/./bindcraft.py", line 108, in <module>
    trajectory = binder_hallucination(design_name, target_settings["starting_pdb"], target_settings["chains"],
  File "/iridisfs/scratch/binder/BindCraft/functions/colabdesign_utils.py", line 28, in binder_hallucination
    af_model = mk_afdesign_model(protocol="binder", debug=False, data_dir=advanced_settings["af_params_dir"],
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/model.py", line 120, in __init__
    params = data.get_model_haiku_params(model_name=model_name, data_dir=data_dir, fuse=True)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/data.py", line 41, in get_model_haiku_params
    return utils.flat_params_to_haiku(params, fuse=fuse)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/utils.py", line 95, in flat_params_to_haiku
    P[scope][name] = jnp.array(array)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 3214, in array
    out_array: Array = lax_internal._convert_element_type(
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 559, in _convert_element_type
    return convert_element_type_p.bind(operand, new_dtype=new_dtype,
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/jax/_src/core.py", line 416, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/jax/_src/core.py", line 420, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/jax/_src/core.py", line 921, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/jax/_src/dispatch.py", line 87, in apply_primitive
    outs = fun(*args)
ValueError: std::bad_cast
```

**Comment by martinpacesa** [comment]
Interesting, I have not encountered this error yet, could you provide a screenshot of the settings you are using and maybe also the input pdb?

**Comment by uuwuyi** [comment]
Hi, I used the example file. Just changed the file path in the PLD1.json
{
    "design_path": "/scratch/binder/test/PDL1/",
    "binder_name": "PDL1",
    "starting_pdb": "/scratch/binder/BindCraft/example/PDL1.pdb",
    "chains": "A",
    "target_hotspot_residues": "56",
    "lengths": [65, 150],
    "number_of_final_designs": 100
}

and changed the SBATCH flags to fit our HPC

#!/bin/bash
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --partition=a100
#SBATCH --mem=80G
#SBATCH --gres=gpu:1
#SBATCH --time 60:00:00
#SBATCH --output=bindcraft_%A.log

# Initialise environment and modules
eval "$(conda shell.bash hook)"
conda activate BindCraft
module load cuda

I checked all the packages installed. They matched the version required.
Here is my jax version to be compatible with our CUDA 12.5.1. If you need other clues, please let me know!
# Name                    Version                   Build  Channel
jax                       0.4.30                   pypi_0    pypi
jax-cuda12-pjrt           0.4.30                   pypi_0    pypi
jax-cuda12-plugin         0.4.30                   pypi_0    pypi
jaxlib                    0.4.30                   pypi_0    pypi

**Comment by martinpacesa** [comment]
This seems to be an error steming from Jax, but not quite sure why. 

1. Could you try to redownload the AlphaFold2 parameters/models to make sure they are not corrupted?
2. Could you try making a new environment from scratch? It seems it helped to fix this issue in some cases: https://github.com/jax-ml/jax/issues/21964

**Comment by uuwuyi** [comment]
Following the steps coreyhowe999 mentioned in  #2 , I managed to reinstall the environment and make it to run now. Thanks for checking!
