### ISSUE TITLE
seems there is compatibility issue using conda on MacOS M1

### ISSUE THREAD

**Issue by biocatchen** [martinpacesa/BindCraft#16]
Hello all, there is the error as shown below. It is run on MacOS M1 system. Not sure if it is better to run on Linux system. thanks a lot. 
jax, jaxlib==0.4.13
python 3.8

(myenv) XX@ BindCraft % python -u /Users/Documents/BindCraft/bindcraft.py --settings 'path/to/settings_target/.json' --filters 'path/to/settings_filters/.json' --advanced 'path/to/settings_advanced/.json'
Traceback (most recent call last):
  File "/Users/Documents/BindCraft/bindcraft.py", line 5, in <module>
    from functions import *
  File "/Users/Documents/BindCraft/functions/__init__.py", line 12, in <module>
    from .colabdesign_utils import *
  File "/Users/Documents/BindCraft/functions/colabdesign_utils.py", line 11, in <module>
    from colabdesign import mk_afdesign_model, clear_mem
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/colabdesign/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/colabdesign/af/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/colabdesign/af/model.py", line 7, in <module>
    from colabdesign.af.alphafold.model import data, config, model, all_atom
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/colabdesign/af/alphafold/model/data.py", line 20, in <module>
    from colabdesign.af.alphafold.model import utils
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/colabdesign/af/alphafold/model/utils.py", line 23, in <module>
    import haiku as hk
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/haiku/__init__.py", line 19, in <module>
    from haiku import data_structures
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/haiku/data_structures.py", line 18, in <module>
    from haiku._src.data_structures import to_haiku_dict
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/haiku/_src/data_structures.py", line 30, in <module>
    from haiku._src import utils
  File "/opt/homebrew/anaconda3/envs/myenv/lib/python3.8/site-packages/haiku/_src/utils.py", line 42, in <module>
    def auto_repr(cls: type[Any], *args, **kwargs) -> str:
TypeError: 'type' object is not subscriptable

**Comment by biocatchen** [comment]
> The software is configured to run on an NVIDIA GPU, I am not quite sure it will run on an M1 mac, and if yes then it would be incredibly slow

Good to know. Thanks for the comments. 
When running on Colab, the execution often gets interrupted midway in many trials. Is there a way to resume the run without starting over? Thank you!

**Comment by martinpacesa** [comment]
Yes, since the data is saved on your google drive, you can just point it to the same output folder again and it will continue
