### ISSUE TITLE
TypeError: Cannot convert numpy.ndarray to numpy.ndarray

### ISSUE THREAD

**Issue by joerloeffler** [martinpacesa/BindCraft#3]
hey, 
after following the steps of reinstalling pyrosetta, I ended up with the following error message when trying to rerun the example locally.

Traceback (most recent call last):
  File "/home/joe/Software/BindCraft/./bindcraft.py", line 52, in <module>
    create_dataframe(trajectory_csv, trajectory_labels)
  File "/home/joe/Software/BindCraft/functions/generic_utils.py", line 262, in create_dataframe
    df = pd.DataFrame(columns=columns)
  File "/home/mojoe/miniforge3/envs/BindCraft/lib/python3.9/site-packages/pandas/core/frame.py", line 876, in __init__
    mgr = dict_to_mgr(
  File "/home/joe/miniforge3/envs/BindCraft/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 443, in dict_to_mgr
    arrays = Series(data, index=columns, dtype=object)
  File "/home/joe/miniforge3/envs/BindCraft/lib/python3.9/site-packages/pandas/core/series.py", line 490, in __init__
    index = ensure_index(index)
  File "/home/joe/miniforge3/envs/BindCraft/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 7647, in ensure_index
    return Index(index_like, copy=copy, tupleize_cols=False)
  File "/home/joe/miniforge3/envs/BindCraft/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 565, in __new__
    arr = sanitize_array(data, None, dtype=dtype, copy=copy)
  File "/home/joe/miniforge3/envs/BindCraft/lib/python3.9/site-packages/pandas/core/construction.py", line 654, in sanitize_array
    subarr = maybe_convert_platform(data)
  File "/home/joe/miniforge3/envs/BindCraft/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 138, in maybe_convert_platform
    arr = lib.maybe_convert_objects(arr)
  File "lib.pyx", line 2538, in pandas._libs.lib.maybe_convert_objects
TypeError: Cannot convert numpy.ndarray to numpy.ndarray

Thank you for your support!

**Comment by LandonGetz** [comment]
I also hit this error after following the solutions in #2, but I managed to get around this by reinstalling jax (guided by some suggestions also in #2). 
`pip install --force-reinstall jax`

**Comment by joerloeffler** [comment]
@LandonGetz this seems to do the trick! Thank you for the suggestion!!!
