### ISSUE TITLE
About DAlphaBall.gcc

### ISSUE THREAD

**Issue by Maikuraky** [martinpacesa/BindCraft#42]
```
/BindCraft/functions/DAlphaBall.gcc: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
WARNING!! DALPHABALL output nan at index 18446744073709551488
DALPHABALL output indicies not matching! 1!=18446744073709551488

ERROR:: Exit from: /home/benchmark/rosetta/source/src/core/scoring/packing/surf_vol.cc line: 164
Traceback (most recent call last):
  File "/BindCraft/bindcraft.py", line 140, in <module>
    trajectory_interface_scores, trajectory_interface_AA, trajectory_interface_residues = score_interface(trajectory_relaxed, binder_chain)
  File "/BindCraft/functions/pyrosetta_utils.py", line 75, in score_interface
    interface_delta_unsat_hbonds = buns_filter.report_sm(pose)
RuntimeError: 

File: /home/benchmark/rosetta/source/src/core/scoring/packing/surf_vol.cc:164
[ ERROR ] UtilityExitException
ERROR: 
```

Hi, thank you for your open source. 
When I run to the end, this error appears. 
Do you have any solution? Thank you

**Comment by Yitian12321** [comment]
Hi, I met the same problem with you. Could you tell me how did you finally solve it?
