### ISSUE TITLE
Bad Zip File issue

### ISSUE THREAD

**Issue by zarbuk** [martinpacesa/BindCraft#45]
Can anyone tell me how to troubleshoot this issue, I have updated to colabdesign v 1.1.2 and it ran successfully until I got this:

Trajectory successful, final pLDDT: 0.86
Starting trajectory took: 0 hours, 29 minutes, 7 seconds

Fixing interface residues: B1,B3,B5,B14,B15,B18,B21,B22,B24,B25,B26,B28,B29,B32,B33,B36,B37,B40,B43,B44,B46,B47,B48,B51,B52,B55,B103
Traceback (most recent call last):
  File "/net/clusterhn.cluster.pssclabs.com/home/zbukhari/BindCraft/bindcraft.py", line 193, in <module>
    complex_prediction_model = mk_afdesign_model(protocol="binder", num_recycles=advanced_settings["num_recycles_validation"], data_dir=$
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/model.py", line 120, in __init__
    params = data.get_model_haiku_params(model_name=model_name, data_dir=data_dir, fuse=True)
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/data.py", line 40, in get_mo$
    params = np.load(io.BytesIO(f.read()), allow_pickle=False)
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/numpy/lib/npyio.py", line 420, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/numpy/lib/npyio.py", line 187, in __init__
    _zip = zipfile_factory(fid)
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by zarbuk** [comment]
The issue could be resolved by editing and giving the full path to alphafold parameters in .py file
