### ISSUE TITLE
Installing with CUDA drivers lower than 525.60

### ISSUE THREAD

**Issue by ajasja** [martinpacesa/BindCraft#5]
The default install script installs CUDA 12. This does not work if you have drivers <525.60.
In that case you have to install cuda 11 and the appropriate jax version.

I will post the install instructions as we figure them out:)

The error is

E1003 09:11:07.171419 1162637 cuda_dnn.cc:503] There was an error before creating cudnn handle (35): cudaErrorInsufficientDriver : CUDA driver version is insufficient for CUDA runtime version

**Comment by martinpacesa** [comment]
For lower than cuda 12 try this:
`conda create --name BindCraft python=3.9 -y
conda activate BindCraft

conda install biopython==1.79 seaborn tqdm jupyter ffmpeg pdbfixer -c anaconda -c conda-forge -y

pip install git+https://github.com/sokrypton/ColabDesign.git
pip uninstall chex --yes
pip uninstall dm-haiku --yes
pip uninstall flax --yes
pip uninstall orbax-checkpoint --yes
pip install "jax[cuda]==0.3.25" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install chex==0.1.5
pip install optax==0.1.7
pip install scipy==1.12.0
pip install dm-haiku==0.0.10
pip install matplotlib==3.7.1`

**Comment by ajasja** [comment]
Thanks! I had to additionally install the toolkit
conda install nvidia/label/cuda-11.3.1::cuda-toolkit

Now I'm at the ptax version error, which I remember I had seen before. So it's progress :)
```
2024-10-03 09:27:57.375754: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:497] The NVIDIA driver's CUDA version is 11.7 which is older than the ptxas CUDA version (12.4.131). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
2024-10-03 09:27:59.461740: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2153] Execution of replica 0 failed: INTERNAL: Failed to load in-memory CUBIN: CUDA_ERROR_INVALID_IMAGE: device kernel image is invalid
```

**Comment by martinpacesa** [comment]
This is always a fight :D

Try something like this:
`CONDA_OVERRIDE_CUDA="11.3.1" conda install scipy"<1.13.0" pdbfixer chex dm-haiku dm-tree joblib ml-collections immutabledict optax jaxlib=*=*cuda11.3* jax==0.3.25 cuda-nvcc==XX.X.* cudnn==XXX.X* -c conda-forge -c anaconda -c nvidia -y`

You'll need to see which nvcc and cudnn verison you need though. This should try to find an appropraite version compatible with jax, chex and stuff

**Comment by ajasja** [comment]
We ended up reusing an AF2 design env we had set up previously that runs BindCraft as well :)

**Comment by ajasja** [comment]
So

```
conda create --name BindCraft python=3.9 -y
conda activate BindCraft

CONDA_OVERRIDE_CUDA=11.7 conda install biopython==1.79 numpy matplotlib scipy"<1.13.0" pdbfixer seaborn tqdm jupyter ffmpeg chex dm-haiku dm-tree joblib ml-collections immutabledict optax jaxlib=*=*cuda11* jax cuda-nvcc flax pyrosetta -c anaconda -c conda-forge -c nvidia --channel https://conda.graylab.jhu.edu/ 

pip install git+https://github.com/sokrypton/ColabDesign.git --no-deps
pip install fsspec
pip install py3Dmol
```

Works! But then I get
`TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

```bash
python -u /home/aljubetic/BindCraft/bindcraft.py --settings "PDL1.json" 
Traceback (most recent call last):
  File "/home/aljubetic/BindCraft/bindcraft.py", line 5, in <module>
    from functions import *
  File "/home/aljubetic/BindCraft/functions/__init__.py", line 12, in <module>
    from .colabdesign_utils import *
  File "/home/aljubetic/BindCraft/functions/colabdesign_utils.py", line 11, in <module>
    from colabdesign import mk_afdesign_model, clear_mem
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/model.py", line 7, in <module>
    from colabdesign.af.alphafold.model import data, config, model, all_atom
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/data.py", line 20, in <module>
    from colabdesign.af.alphafold.model import utils
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/utils.py", line 23, in <module>
    import haiku as hk
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/__init__.py", line 55, in <module>
    from haiku.experimental import flax
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/flax.py", line 18, in <module>
    from haiku._src.flax.flax_module import Module
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/haiku/_src/flax/flax_module.py", line 20, in <module>
    import flax.core
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/flax/__init__.py", line 24, in <module>
    from flax import core
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/flax/core/__init__.py", line 15, in <module>
    from .axes_scan import broadcast as broadcast
  File "/home/aljubetic/conda/envs/BindCraft/lib/python3.9/site-packages/flax/core/axes_scan.py", line 41, in <module>
    length: int | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by martinpacesa** [comment]
yeah...can you try to downgrade to jax 0.4.23?

**Comment by zarbuk** [comment]
This is on downgrading to jax 0.4.23

Traceback (most recent call last):
  File "/home/zbukhari/BindCraft/bindcraft.py", line 5, in <module>
    from functions import *
  File "/net/clusterhn.cluster.pssclabs.com/home/zbukhari/BindCraft/functions/__init__.py", line 12, in <module>
    from .colabdesign_utils import *
  File "/net/clusterhn.cluster.pssclabs.com/home/zbukhari/BindCraft/functions/colabdesign_utils.py", line 11, in <module>
    from colabdesign import mk_afdesign_model, clear_mem
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/model.py", line 7, in <module>
    from colabdesign.af.alphafold.model import data, config, model, all_atom
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/data.py", line 20, i$
    from colabdesign.af.alphafold.model import utils
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/utils.py", line 23, $
    import haiku as hk
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/__init__.py", line 55, in <modul$
    from haiku.experimental import flax
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/flax.py", line 18, in <module>
    from haiku._src.flax.flax_module import Module
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/_src/flax/flax_module.py", line 20, in <modul$
    import flax.core
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/flax/__init__.py", line 24, in <module>
    from flax import core
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/flax/core/__init__.py", line 15, in <module>
    from .axes_scan import broadcast as broadcast
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/flax/core/axes_scan.py", line 41, in <module>
    length: int | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
srun: error: gpu001: task 0: Exited with exit code 1

**Comment by zarbuk** [comment]
Please let is know a workaround for this ? or if its not possible then maybe someone mentioned their environment for af2 worked fine with Bindcraft, maybe  if you can share that?

**Comment by zarbuk** [comment]
> We ended up reusing an AF2 design env we had set up previously that runs BindCraft as well :)

can you give specification of this environment?
