### ISSUE TITLE
DAlphaBall fails to load libgfortran.so.5 in conda environment

### ISSUE THREAD

**Issue by suzuki-sh** [martinpacesa/BindCraft#65]
Thank you for your excellent work on the BindCraft project. 
I encountered a minor issue while running the PDL1.pdb example, which I was able to resolve, and I'm reporting it here.

## Problem
When running the PDL1.pdb example locally, an error occurs due to DAlphaBall being unable to find libgfortran.so.5.

## Environment
- OS: Ubuntu 22.04.4 LTS
- Conda version: 24.7.1
- BindCraft version: v1.1.0
- CUDA version: 12.2

## Error Message
- run.sh
```
python -u ./bindcraft.py \
    --settings './settings_target/PDL1.json' \
    --filters './settings_filters/default_filters.json' \
    --advanced './settings_advanced/4stage_multimer.json'
```

- terminal
```
(base) $ conda activate BindCraft
(BindCraft) $ bash run.sh
Available GPUs:

...

Trajectory successful, final pLDDT: 0.91
Starting trajectory took: 0 hours, 7 minutes, 19 seconds

/home/suzuki/workspace/protein-design/BindCraft/functions/DAlphaBall.gcc: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
WARNING!! DALPHABALL output nan at index 18446744073709551488
DALPHABALL output indicies not matching! 1!=18446744073709551488
ERROR:: Exit from: /home/benchmark/rosetta/source/src/core/scoring/packing/surf_vol.cc line: 164
Traceback (most recent call last):
  File "/home/suzuki/workspace/protein-design/BindCraft/./bindcraft.py", line 141, in <module>
    trajectory_interface_scores, trajectory_interface_AA, trajectory_interface_residues = score_interface(trajectory_relaxed, binder_chain)
  File "/home/suzuki/workspace/protein-design/BindCraft/functions/pyrosetta_utils.py", line 75, in score_interface
    interface_delta_unsat_hbonds = buns_filter.report_sm(pose)
RuntimeError: 
File: /home/benchmark/rosetta/source/src/core/scoring/packing/surf_vol.cc:164
[ ERROR ] UtilityExitException
ERROR:

```

## Solution
The issue can be resolved by adding the conda environment's lib directory to LD_LIBRARY_PATH:
```bash
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib
```

***
Thanks.

**Comment by martinpacesa** [comment]
Thank you for the report!
