### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by uuwuyi** [martinpacesa/BindCraft#7]
Hi @martinpacesa , thanks for the work! I'm trying to run the example. However, it returned an index error. Log information below. I'm not sure which part is having problem. Any help is appreciated!

```
PyRosetta-4 2024 [Rosetta PyRosetta4.Release.python39.ubuntu 2024.24+release.ca096dac4f43ee5ee195f87f3703a520fcf60cf9 202
4-06-14T16:57:57] retrieved from: http://www.pyrosetta.org
Starting trajectory: PDL1_l148_s558576
WARNING: 'model_1_multimer_v3' not found
WARNING: 'model_2_multimer_v3' not found
WARNING: 'model_3_multimer_v3' not found
WARNING: 'model_4_multimer_v3' not found
WARNING: 'model_5_multimer_v3' not found
2024-10-03 22:59:22.089800: W external/xla/xla/service/gpu/nvptx_compiler.cc:765] The NVIDIA driver's CUDA version is 12.
4 which is older than the ptxas CUDA version (12.6.77). Because the driver is older than the ptxas version, XLA is disabl
ing parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provide
d CUDA forward compatibility packages.
Stage 1: Test Logits
Traceback (most recent call last):
  File "/iridisfs/scratch/binder/BindCraft/./bindcraft.py", line 108, in <module>
    trajectory = binder_hallucination(design_name, target_settings["starting_pdb"], target_settings["chains"],
  File "/iridisfs/scratch/binder/BindCraft/functions/colabdesign_utils.py", line 97, in binder_hallucination
    af_model.design_logits(iters=50, e_soft=0.9, models=design_models, num_models=1, sample_models=advanced_settings["sam
ple_models"], save_best=True)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 346, in design_lo
gits
    self.design(iters, **kwargs)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 340, in design
    self.step(lr_scale=lr_scale, num_recycles=num_recycles,
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 206, in step
    self.run(num_recycles=num_recycles, num_models=num_models, sample_models=sample_models,
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 89, in run
    model_nums = self._get_model_nums(num_models, sample_models, models)
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 71, in _get_model_nums
    ns = [ns[n if isinstance(n,int) else ns_name.index(n)] for n in models]
  File "/home/.conda/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 71, in <listcomp>
    ns = [ns[n if isinstance(n,int) else ns_name.index(n)] for n in models]
IndexError: list index out of range
```

**Comment by KotaroTsuboyama** [comment]
This should be due to lacking of alphafold weights. You can check if the files are in BindCraft//params/ directory. And if not you can do that manually:

`mkdir -p ${install_dir}/params/
cd ${install_dir}/params/
wget -P ${install_dir}/params/ https://storage.googleapis.com/alphafold/alphafold_params_2022-12-06.tar
tar -xvf ${install_dir}/params/alphafold_params_2022-12-06.tar
rm ${install_dir}/params/alphafold_params_2022-12-06.tar`
${install_dir} should be your BindCraft directory

**Comment by martinpacesa** [comment]
Indeed, make sure the params were correctly downloaded
