### ISSUE TITLE
DAlphaBall.gcc: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by KotaroTsuboyama** [martinpacesa/BindCraft#8]
Hi this is great work, so we would like to utilize this pipeline as soon as possible!!

I installed BindCraft in nvidia/cuda:12.2.2-cudnn8-devel-ubuntu22.04 docker image.

Even with the latest install_bindcraft.sh, I got the exact same error as #2, so as suggested in https://github.com/martinpacesa/BindCraft/issues/2#issuecomment-2388769334, I manually installed pyrosetta from wheel via 'pip install XX.whl' command.

Then I also got the following error:
`AttributeError: module 'Bio.PDB.Polypeptide' has no attribute 'three_to_one'`
I found my conda env has biopython==1.84 (not sure why?)
so I downgraded biopython via
`conda install conda-forge::biopython==1.79`

Then overall, the pipeline works, but in the step4 I also got the following error:

> Trajectory successful, final pLDDT: 0.86
Starting trajectory took: 0 hours, 4 minutes, 20 seconds
/projects/00_tools/BindCraft/functions/DAlphaBall.gcc: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
WARNING!! DALPHABALL output nan at index 18446744073709551488
DALPHABALL output indicies not matching! 1!=18446744073709551488
ERROR:: Exit from: /home/benchmark/rosetta/source/src/core/scoring/packing/surf_vol.cc line: 164
Traceback (most recent call last):
  File "/projects/00_tools/BindCraft/bindcraft.py", line 140, in <module>
    trajectory_interface_scores, trajectory_interface_AA, trajectory_interface_residues = score_interface(trajectory_relaxed, binder_chain)
  File "/projects/00_tools/BindCraft/functions/pyrosetta_utils.py", line 75, in score_interface
    interface_delta_unsat_hbonds = buns_filter.report_sm(pose)
RuntimeError: 
File: /home/benchmark/rosetta/source/src/core/scoring/packing/surf_vol.cc:164
[ ERROR ] UtilityExitException
ERROR: 

I don't think my linux workstation has the following dir and file (this is probably yours?):
`/home/benchmark/rosetta/source/src/core/scoring/packing/surf_vol.cc:164`
So I guess this might be the cause? I'm now feeling we need to compile DAlphaBall tool on our environment, but if so how can I do that and integrate the new complied file with your pipeline? Or should I install different version of libgfortran?
Any suggestions are really helpful!

**Comment by KotaroTsuboyama** [comment]
OK I think I can fix this issue by myself.

FYI, I compiled the tool using the following tool on docker:
https://github.com/outpace-bio/DAlphaBall
dalphaball_docker_build.sh ../tmt/

Then I installed the tool by the following command:
conda install dalphaball -c ./tmt/

While installing the tool, conda installed new libgfortran, so this might a key for fixing the issue?
`    gmp-6.2.1                  |       h295c915_3         544 KB
    libgfortran-ng-8.2.0       |       hdf63c60_1         1.3 MB
    libgfortran5-14.1.0        |       hc5f4f2c_1         1.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.3 MB

The following NEW packages will be INSTALLED:

  dalphaball         tmt/linux-64::dalphaball-1.0-h3218e01_0 
  gmp                pkgs/main/linux-64::gmp-6.2.1-h295c915_3 
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-8.2.0-hdf63c60_1 
  libgfortran5       conda-forge/linux-64::libgfortran5-14.1.0-hc5f4f2c_1 
`
And now I can passed the stage4!
